test:
  adapter: postgresql
  encoding: unicode
  database: happy_nel_test
  pool: 5
  username: ice
  password: "ice123"

development:
  adapter: postgresql
  encoding: unicode
  database: happy_nel
  pool: 5
  username: ice
  password: "ice123"

production:
  adapter: postgresql
  encoding: unicode
  database: happy_nel
  pool: 5
